# HTML Head settings
html:
  title: DxMorgan | Testeo

# Main container settings
main:
  title: 游댥 Dexter Morgan 游눌

# Blocks list
blocks:
  - title: Telegram 
    icon: telegram
    url: https://t.me/dxmorgan

#  - title: Discord
#    icon: discord
#    url: https://discord.lacrypta.com.ar

#  - title: Quiero participar!
#    icon: voluntary
#    url: https://docs.google.com/forms/d/e/1FAIpQLSfMM_fDXrBVlxujPy4yhYRuhHWrtPSvoD8QRCKuHzZXgsFFzg/viewform

  - title: Github
    icon: github
    url: https://github.com/dxm0rg4n/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/chelodxmg

  - title: PlayFC Movies
    icon: url
    url: https://t.me/playfc

  - title: WhatsApp
    icon: whatsapp
    url: https://api.whatsapp.com/send/?phone=%2B541128073054&text=Hola+que+tal&type=phone_number&app_absent=0

  - title: "Mejores Fraces"
    icon: youtube
    url: https://www.youtube.com/watch?v=F2ZqsqfgsEc






#--------------------------------------
# ESTO ES UN COMENTARIO
# Todo lo que est치 a la derecha de # es solo para nosotros

#version: 0.3.5 # NO TOCAR

# HODL username
# username: "USUARIO" # < TU_USUARIO@hodl.ar

# NOSTR Settings
# nostr: # Sin el # adelante
#   npub: "TU_PUB" # Entre comillas dobles

# Configuraci칩n Global
#html:
# title: Este valor no funciona porque esta comentado
#  title: Links | Mi Nombre # Este es el T칤tulo que aparece en la pesta침a de navegador

# Colores de plantilla
#theme:
#  background_color: "#f9fafb"
  # cover_color: "#ff7070"

# Configuraci칩n Central
#main:
#  title: Mi Nombre # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
#blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que est치 en blanco
  # Sacale 

#  - title: Instagram
#    icon: instagram
#    url: https://www.instagram.com/lacryptaok/

# - title: Twitter
#   icon: twitter
#   url: https://twitter.com/TU-USUARIO
    
# - title: LinkedIn # Este es el nombre del bot칩n
#   icon: linkedin # Este es el nombre del icono (si queres a침adir una red social nueva, prest치 atencion que es todo con min칰scula)
#   url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionar치 al hacer click

# - title: Github
#   icon: github
#   url: https://github.com/TU-USUARIO

# - title: Sitio Web
#   icon: url
#   url: https://www.TU-WEB.com

# - title: Telegram
#   icon: telegram
#   url: https://t.me/TU-USUARIO
    
# Guard치 el archivo haciendo click en Commit Changes, abajo
# Volv칠 a las instrucciones
